version: "3.8"

services:
  # write for postgres
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hoteldb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - server

  server:
    build: ./server
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/hoteldb?connect_timeout=300
      DEBUG: True
      ALLOWED_HOSTS: localhost
      PORT: 8000
    networks:
      - server
      - client

  client:
    build: ./client
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - client

volumes:
  postgres_data:

networks:
  server:
    driver: bridge
  client:
    driver: bridge
